name: KICS Security Scan

on: [push]

jobs:
  kics_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run KICS Scan (output SARIF and JSON)
        uses: checkmarx/kics-github-action@v2.1.13
        with:
          path: .
          output_path: myResults
          output_formats: 'sarif,json'
          ignore_on_exit: results

      - name: Show KICS JSON (optional)
        run: |
          if [ -f myResults/results.json ]; then
            cat myResults/results.json
          else
            echo "No KICS JSON results found."
          fi

      - name: Upload SARIF to GitHub Security tab
        if: ${{ success() && (hashFiles('myResults/results.sarif') != '') }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: myResults/results.sarif
