name: KICS IaC Scan

on: [push, pull_request]

jobs:
  kics_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run KICS Scan (ignore failures)
        uses: checkmarx/kics-github-action@v2.1.13
        with:
          path: 'terraform'
          ignore_on_exit: results
          output_path: myResults/
      - name: Display KICS results
        run: cat myResults/results.json
