name: KICS Security Scan (Severity Mapped)

on:
  push:
  pull_request:

jobs:
  kics_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run KICS (JSON output only)
        uses: checkmarx/kics-github-action@v2.1.13
        with:
          path: .
          output_path: myResults
          output_formats: 'json'
          ignore_on_exit: results

      - name: Show raw KICS JSON (first lines)
        run: |
          ls -l myResults || true
          if [ ! -f myResults/results.json ]; then
            echo "results.json missing"; exit 1
          fi
          head -n 80 myResults/results.json

      - name: Convert to severity-mapped SARIF
        run: |
          mkdir -p custom-sarif
          python3 scripts/kics_json_to_sarif.py myResults/results.json custom-sarif/results-with-severity.sarif
          ls -l custom-sarif
          head -n 40 custom-sarif/results-with-severity.sarif || true

      - name: Verify SARIF exists
        run: test -f custom-sarif/results-with-severity.sarif

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: custom-sarif/results-with-severity.sarif

      - name: Upload artifacts (debug)
        uses: actions/upload-artifact@v4
        with:
          name: kics-severity-artifacts
          path: |
            myResults/results.json
            custom-sarif/results-with-severity.sarif
