name: KICS Security Scan

on: [push]
#  push:
 #   branches: [main]
  #pull_request:
   # branches: [main]


jobs:
  kics_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up results directory
        run: mkdir -p myResults

      - name: Install KICS
        run: |
          curl -sfL https://raw.githubusercontent.com/Checkmarx/kics/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run KICS scan (scan all files, output SARIF and JSON)
        run: |
          kics -p . -o myResults/ --report-formats sarif,json

      - name: Show KICS JSON (optional, for debugging)
        run: |
          if [ -f myResults/results.json ]; then
            cat myResults/results.json
          else
            echo "No KICS JSON results found."
          fi

      - name: Upload SARIF to GitHub Security tab
        if: ${{ success() && (hashFiles('myResults/results.sarif') != '') }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: myResults/results.sarif
