name: KICS Security Scan (Severity Mapped)

on:
  push:
  pull_request:

jobs:
  kics_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run KICS (JSON output)
        uses: checkmarx/kics-github-action@v2.1.13
        with:
          path: .
          output_path: myResults
          output_formats: 'json'
          ignore_on_exit: results

      - name: Inspect myResults permissions
        run: |
          ls -ld myResults || true
          ls -l myResults || true

      - name: (Optional) Fix permissions if needed
        run: |
          if [ -d myResults ]; then
            sudo chown -R $USER:$USER myResults || true
            chmod -R u+w myResults || true
          fi

      - name: Show snippet of raw KICS JSON
        run: |
          if [ -f myResults/results.json ]; then
            head -n 120 myResults/results.json
          else
            echo "results.json not found"; exit 1
          fi

      - name: Write severity mapping script
        run: |
          mkdir -p scripts
          cat > scripts/kics_json_to_sarif.py <<'PYEOF'

      - name: Generate severity-mapped SARIF
        run: |
           mkdir -p custom-sarif
           python3 scripts/kics_json_to_sarif.py myResults/results.json custom-sarif/results-with-severity.sarif

      - name: Upload severity-mapped SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: custom-sarif/results-with-severity.sarif

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kics-severity-artifacts
          path: |
            myResults/results.json
            custom-sarif/results-with-severity.sarif
