name: Trivy Infrastructure Scan

#on:
  push:
    branches:
      - main
  pull_request:


#jobs:
  build:
    name: Trivy IaC Build and Scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.65.0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: List all potential IaC files (debug)
        run: |
          echo "Found these candidate IaC files:"
          find . -type f \( -name "*.tf" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" -o -name "*.template" -o -name "*.ymkl" \)

      - name: Trivy Debug (show all findings, plain output)
        run: |
          mkdir -p trivy-reports
          echo "===== Trivy All Results (Plain Output) ====="
          find . -type f \( -name "*.tf" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" -o -name "*.template" -o -name "*.ymkl" \) > trivy-reports/iac_files.txt
          while read file; do
            echo "---- $file ----"
            trivy config "$file" || true
          done < trivy-reports/iac_files.txt

      - name: Trivy IaC SARIF scan (directory mode)
        run: |
          mkdir -p trivy-reports
          trivy config --format sarif --output trivy-reports/trivy-results.sarif .

      - name: Check if SARIF has results
        id: sarif-check
        run: |
          if jq -e '.runs[0].results | length == 0' trivy-reports/trivy-results.sarif; then
            echo "No findings in SARIF"
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "Findings present in SARIF"
            echo "found=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload Trivy scan results to GitHub Security tab
        if: steps.sarif-check.outputs.found == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-reports/trivy-results.sarif'

      - name: Upload SARIF artifact (for manual inspection)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-sarif
          path: trivy-reports/trivy-results.sarif
